#!/usr/bin/env bash

chmod a+x bin/startServerInTestingMode

docker-compose -f docker-compose/ci.yml up -d

echo "[$(date)] - Awaiting for the container to be ready..."

n=0
until [ "$n" -ge 30 ]
do
   docker exec -t backend npm -v && break  # substitute your command here
   n=$((n+1))
   echo "."
   sleep 1
done

echo "[$(date)] - The container is ready: starting..."

npm run test:func
FUNC_TESTS_EXIT_CODE=$? # store the tests exit code

if [ $FUNC_TESTS_EXIT_CODE -eq 0 ]
then
  echo ''
  echo ''
  echo -e "\e[32m Functional tests passed !\e[0m"
  echo ''
  echo ''
else
  echo ''
  echo ''
  echo -e "\e[31m Functional tests failed...\e[0m"
  echo ''
  echo ''
fi

#docker-compose -f docker-compose/ci.yml kill
exit $FUNC_TESTS_EXIT_CODE