#!/usr/bin/env bash

chmod a+x bin/startServerInTestingMode

docker-compose -f docker-compose/ci.yml up -d

echo "[$(date)] - Starting..."

n=0
until [ "$n" -ge 30 ]
do
   pm run test:func && break  # substitute your command here
   n=$((n+1))
   sleep 1
done
FUNC_TESTS_EXIT_CODE=$? # store the tests exit code

if [ $FUNC_TESTS_EXIT_CODE -eq 0 ]
then
  echo ''
  echo ''
  echo -e "\e[32m Functional tests passed !\e[0m"
  echo ''
  echo ''
else
  echo ''
  echo ''
  echo -e "\e[31m Functional tests failed...\e[0m"
  echo ''
  echo ''
fi

docker-compose -f docker-compose/ci.yml kill
exit $FUNC_TESTS_EXIT_CODE

