version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  unit-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test:unit
  functional-test:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Launch stack
          command: ./start-dev
      - run:
          name: Run functional testing
          command: npm run test:func

workflows:
    main:
      jobs:
        - scan:
            context: SonarCloud
        - unit-test
        - functional-test
