version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  unit-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test:unit
  functional-test:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Launch stack
          command: ./start-dev
      - run:
          name: Run functional testing
          command: npm run test:func

workflows:
    main:
      jobs:
        - unit-test
        - functional-test
