version: 2.1
orbs:
  node: circleci/node@1.1.6
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test:unit
workflows:
    build-and-test:
      jobs:
        - build-and-test
    main:
      jobs:
        - build:
            context: SonarCloud
