version: '3'

services:
  backend:
    image: j33f/node-docker-container
    container_name: backend
    command: bash -c "mv /var/pm2Config/pm2-dev.json /var/pm2Config/config.json && chmod 775 /var/startScripts/run-ci.sh && /var/startScripts/run-ci.sh"
    volumes:
      - ..:/var/app:cached
      - ./config:/var/pm2Config
      - ./scripts:/var/startScripts
    cap_add:
      - SYS_PTRACE
    depends_on:
      - redis
      - mongo
      - mailout
    dns:
      - 208.67.222.222
      - 208.67.220.220
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8842:8842"
    environment:
      - NODE_ENV=${NODE_ENV:-development}

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ulimits:
      nofile: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=mongo-admin"
      - "MONGO_INITDB_ROOT_PASSWORD=1Lnl4ZEg!gPdF!zGKdILfww"
      - "MONGO_INITIDB_DATABASE=admin"

  mailout:
    image: j33f/alpine-postfix
    container_name: mailout
    restart: always
    environment:
      - DOMAIN=yggdrasil.com.test
      - HOSTNAME=yggdrasil.com.test
