version: '3'

services:
  backend:
    image: j33f/node-docker-container:pupeteer-unoconv
    container_name: backend
    command: sh -c 'chmod 755 /run.sh && /run.sh'
    volumes:
      - "..:/var/app:delegated"
      - "./scripts/run-concourse.sh:/run.sh:delegated"
      - "./config/pm2-dev.json:/config/pm2.json:delegated"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - redis
      - mongo
      - mailout
    dns:
      - 208.67.222.222
      - 208.67.220.220
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8842:8842"
      - "9229:9229"
      - "9230:9230"
    environment:
      - NODE_ENV=${NODE_ENV:-development}

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ulimits:
      nofile: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/mongo:/data/db:delegated
      - /data/mongoDumps:/data/dumps:delegated
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=mongo-admin"
      - "MONGO_INITDB_ROOT_PASSWORD=1Lnl4ZEg!gPdF!zGKdILfww"
      - "MONGO_INITIDB_DATABASE=admin"

  mailout:
    image: j33f/alpine-postfix
    container_name: mailout
    restart: always
    environment:
      - DOMAIN=nobs-consulting.com
      - HOSTNAME=nobs-consulting.com
