version: '3'

services:
  backend:
    build: ..
    container_name: backend
    volumes:
      - ../fileStorage:/var/fileStorage:defered
      - ../.yggdrasilrc:/var/app/.yggdrasilrc:defered
    cap_add:
      - SYS_PTRACE
    depends_on:
      - redis
      - mongo
      - mailout
    dns:
      - 208.67.222.222
      - 208.67.220.220
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8842:8842"
    environment:
      - NODE_ENV=${NODE_ENV:-production}

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ulimits:
      nofile: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../data/mongo:/data/db:cached
      - ../data/mongoDumps:/data/dumps:cached
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=mongo-admin"
      - "MONGO_INITDB_ROOT_PASSWORD=1Lnl4ZEg!gPdF!zGKdILfww"
      - "MONGO_INITIDB_DATABASE=admin"

  mailout:
    image: j33f/alpine-postfix
    container_name: mailout
    restart: always
    environment:
      - DOMAIN=nobs-consulting.com
      - HOSTNAME=nobs-consulting.com
